#:schema node_modules/wrangler/config-schema.json
name = "learn"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

[ai]
binding = "AI"